# Configuración del plugin SabbathMode
# Puedes personalizar los mensajes de denegación aquí.
# Variables disponibles:
#   {zone_id}: Será reemplazado por la zona horaria detectada del jugador (ej. America/Mexico_City).
#   {saturday_sunset_time}: Será reemplazado por la hora de finalización del Sabbath en la zona horaria del jugador (ej. 18:00).
messages:
  sabbath-denied: "&cEl servidor está cerrado hoy.\n\n&79. Seis días trabajarás, y harás toda tu obra;\n&710. mas el séptimo día es reposo para Jehová tu Dios;\n&6Exodo 20:9-10\n\n&cAcceso restringido en tu zona horaria (&e{zone_id}&c).\n&cPuedes ingresar a partir del &eSábado &ca las &e{saturday_sunset_time} &c(hora local)."

# Configuración para TESTING. ESTO DEBE SER DESACTIVADO EN PRODUCCIÓN.
testing:
  # Habilita o deshabilita el modo de prueba. Deshabilita en producción.
  enabled: false
  # Define el día y la hora de inicio del Sabbath para pruebas (formato HH:mm)
  # Día: MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY, SUNDAY
  # Ej: Para que el Sabbath empiece el Jueves a las 10:00 AM (hora local del jugador)
  sabbath-start-day: THURSDAY
  sabbath-start-time: "10:00"
  # Define el día y la hora de fin del Sabbath para pruebas (formato HH:mm)
  # Ej: Para que el Sabbath termine el Jueves a las 11:00 AM (hora local del jugador)
  sabbath-end-day: THURSDAY
  sabbath-end-time: "11:00"