# Configuración del plugin SabbathMode
# Puedes personalizar los mensajes de denegación aquí.
# Variables disponibles:
#   {zone_id}: Será reemplazado por la zona horaria detectada del jugador (ej. America/Mexico_City).
#   {saturday_sunset_time}: Será reemplazado por la hora de finalización del Sabbath en la zona horaria del jugador (ej. 18:00).
messages:
  sabbath-denied: "&c¡Hola! En tu zona horaria ({zone_id}), es Sábado desde la puesta de sol hasta la puesta de sol. &cEl acceso está restringido durante este período por motivos religiosos. &cPor favor, intenta conectarte de nuevo después de las {saturday_sunset_time} (hora local)."

# Configuración para TESTING. ESTO DEBE SER DESACTIVADO EN PRODUCCIÓN.
testing:
  # Habilita o deshabilita el modo de prueba. Deshabilita en producción.
  enabled: true
  # Define el día y la hora de inicio del Sabbath para pruebas (formato HH:mm)
  # Día: MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY, SUNDAY
  # Ej: Para que el Sabbath empiece el Jueves a las 10:00 AM (hora local del jugador)
  sabbath-start-day: THURSDAY
  sabbath-start-time: "10:00"
  # Define el día y la hora de fin del Sabbath para pruebas (formato HH:mm)
  # Ej: Para que el Sabbath termine el Jueves a las 11:00 AM (hora local del jugador)
  sabbath-end-day: THURSDAY
  sabbath-end-time: "11:00"